### ISSUE TITLE
urgent BabelTranslation not working anymore once modx updated to 2.3.3

### ISSUE THREAD

**Issue by elz64** [mikrobi/babel#101]
As everything used to be ok in my current project, Once Revo was updated from 2.3.2 to 2.3.3, all BabelTranslation links are now empty!...

ex:
```html
<a href="[[~[[BabelTranslation? &contextKey=`[[*context_key]]` &resourceId=`2`]]]]"
   class="btn btn-cta1 btn-flat-whiteBleu btn-lg btn-xl"
   role="button"
   title="[[%i18n.buylink_title? &language=`[[++cultureKey]]` &namespace=`i18ncustom`]]">
    .......
</a>
```
this href is now not resolved as it used to be in 2.3.2 (I reversed from 2.33 to 2.32 and everything came back and work again).
Uptading to Babel 3.0 beta2 does NOT resolve this (and I dont understand the new Flag logic)

Really Thank you

**Comment by goldsky** [comment]
You mean with 3.0.0-beta2 it works in 2.3.2 but not in 2.3.3?

**Comment by goldsky** [comment]
Try to update BabelTranslation snippet on this part:

```php
/* get snippet properties */
$resourceId = intval($modx->getOption('resourceId',$scriptProperties));
//if(empty($resourceId) && !empty($modx->resource) && is_object($modx->resource)) {
//	$resourceId = $modx->resource->get('id');
//} else {
//	return;
//}
if (empty($resourceId)) {
    if (!empty($modx->resource) && is_object($modx->resource)) {
        $resourceId = $modx->resource->get('id');
    } else {
        return;
    }
}
```

**Comment by goldsky** [comment]
https://github.com/mikrobi/babel/commit/1e8308cb5bdf8aeaac20b39778689caf9360de12

**Comment by elz64** [comment]
I meant 2.25 was ok before modx 3.33 and NOT right after Modx update (end neither with the Beta2 of Babel)

**Comment by elz64** [comment]
Your patche seams to give results.
However How can I get ALL flags back 5I have aonly 2 language and the current one is no more at scree, so theire is now only the OTHER one, making think the NOT current choosen language IS the current language !..

**Comment by goldsky** [comment]
Ehm... can you turn auto-translate to off?
I couldn't understand your saying.

**Comment by elz64** [comment]
Well
This is the first time my " self translated" English is not understood  
Ok
Before with Babel 2.x the babelflag logic used to display every flag ( one per language, including the current active one) and we could play with css to manage the way the current active language should be shown. 
Now with Banel 3, the babelflag show ONLY the flags for language that are not active. The active one has simply vanish. 
From an ergonomic point of view especially when you have only 2 languages because with one visible flag it's ambiguous. 

Hope you got the idea. 
Regards

(depuis iPhone)

**Comment by goldsky** [comment]
Oh, that,
Try to add this to snippet call
```
&showCurrent=`1`
```

Btw, I think BabelLinks has same bug with this BabelTranslation's, so pls
fix the PHP code manually first, I'll update the package soon.

**Comment by elz64** [comment]
Hi,

Can you clarify what modification should be done in BAbelLinks  please ?

thank you



*And I'm facing another issue:*

Once logged in (Frontent [login package]  )
 * Flags disappears* and, again, some Babeltranslations links are empty.
(but not all of them !??)


Regards

2015-02-17 0:07 GMT+01:00 rico <notifications@github.com>:

**Comment by elz64** [comment]
and a last thing:
Error log is now full of :

"[2015-02-18 16:00:38] (ERROR @ /index.php) Could not load context: en
[2015-02-18 16:00:38] (ERROR @ /index.php) Could not load context: en"

Thank you

2015-02-18 16:04 GMT+01:00 Eric Lacomblez <elz064@gmail.com>:
