### ISSUE TITLE
Less clicking in MODX manager Babel button

### ISSUE THREAD

**Issue by Froggiewalker** [mikrobi/babel#103]
There is a nice new Babel button in the manager, thanks for that.

Just a little usability idea:
What about to open the languages menu after mouse over, like MODX Manager top menu?
And what about to navigate to other language resource on click just on the language name, not having to move right to Open/Unlink menu?
One click less and some mouse moving less is good :-)
Thanks

**Comment by goldsky** [comment]
I'm not sure I follow you.
From my point of view, the current navigation has different menu based on the existence of linked resource, and another option to change/update that connection.

> And what about to navigate to other language resource on click just on the language name

And how about "unlink"-ing the resource?
And we have 2 conditions: linked and unlinked.
They have different menu.

**Comment by Froggiewalker** [comment]
I know it's different. My suggest didn't involve elimination of second level menu – **create translate** and **link to existing** in case of untranslated resources and only **unlink resouce** in case of translated. I would only make first level menu item – **language (context)** – clickable to navigate to linked resource, because this is much more frequently performed action then linking, unlinking or creating translate.
Neither expanding the first level menu on hovering the button wouldn't matter the differency.

**Comment by Froggiewalker** [comment]
To clarify my puzzled ideas :-)
```
[English (web)]
       |
     hover
       |
       V                  ,-click--> go to linked Nachrichten
+----------------------+ /
| $ Deutsch (de)     > | ---hover--> +----------------------------+
| $ Español (es)     > |             | % Unlink Noticias (42)     |
|   Čeština (sc)     > |             +----------------------------+
|   Slovenština (sk) > |
|   Română (ro)      > |  ,-click--> do nothing
|   Po naszymu (te)  > | /
|   Русский (ru)     > | ---hover--> +----------------------------+
+----------------------+             | * Create translate         |
                                     | $ Link to existing resouce |
                                     +----------------------------+
```
`$` is chain icon
`%` is broken chain icon
`*` is pencil and arrow icon

I would understand if it's not suitable with Your opinions. I just think that eliminating some clickwork when navigating between existing translations would save considerable amount of time.
