### ISSUE TITLE
Link to existing resource ID select does not work

### ISSUE THREAD

**Issue by elz64** [mikrobi/babel#106]
Hi,

May be I'm wrong, but I'm facing this issue after trying to relink one page from Web to its equivalent on EN context.
The select field,  proposing a list of" ID of target", does not reply and stays locked on the sentence saying "please select a container in tree...." (no choice appears, the list does not roll down) or the parent id number of the current page appears and that's all.

However the second input (to enter manually a page title) seams ok ( but "&nbsp" appears in it)

**Comment by goldsky** [comment]
> no choice appears, the list does not roll down
You need to select the resource on the left tree, just like how you change resource's parent.

> but "&nbsp" appears in it
You can ignore it for now, it's for empty selection.
I'll try to figure out to remove that text.
