### ISSUE TITLE
option to hide contextkey from manager menu

### ISSUE THREAD

**Issue by degoya** [mikrobi/babel#107]
when i.E. the web context is used for the english version of the site then it is a bit confusing for the editor to get the contextKey "(web)" displayed next to the Word English. It would be nice to have a option to disable the display in the manager or replace it with the cultureKey or context name.

**Comment by goldsky** [comment]
Sorry, I don't follow.
Screenshot?

**Comment by vierkantemeter** [comment]
I guess he means the (web) in this example:

![voila_capture 2015-03-18_05-53-21_pm](https://cloud.githubusercontent.com/assets/487567/6714300/d2a9b3d4-cd97-11e4-95c0-5eedcc23f1ad.jpg)

**Comment by degoya** [comment]
@vierkantemeter : exactly. 
sorry, lost a bit focus and forgot to add a screenshot
