### ISSUE TITLE
[Question] How come BabelLinks is empty when no translations are available?

### ISSUE THREAD

**Issue by hugopeek** [mikrobi/babel#108]
> Url to linked translation (or site_url of specific language if there is no translated resource available).

The docs mention that if the url placeholder is empty, it defaults to the site_url of that context.. This is what I'm looking for as well, so that people can still switch language if no translation of that specific page is available.

Now, BabelLinks remains empty if no resources are linked. Is this expected behavior, or a bug?

**Comment by goldsky** [comment]
I've [modified the behavior](https://github.com/mikrobi/babel/commit/5d12092f6ae1d5271fd021c256fa1f6a7ed2feda), but try to use &includeUnlinked=`1` to revert it.

**Comment by hugopeek** [comment]
Ah thanks, tried it, but it doesn't seem to be working in my case.. Language selectors remain empty on unlinked pages. I made sure I'm on latest MODX and Babel versions, and cleared all the caches.

**Comment by goldsky** [comment]
it's a bug, and a fix has been made.
