### ISSUE TITLE
Issues linking & unlinking documents in Modx 2.4 not pointing to the correct resource.

### ISSUE THREAD

**Issue by BigBlockStudios** [mikrobi/babel#113]
Report from a client during testing:

Unlinking,  if you follow a workflow of creating the
document in English and then the French from the Babel button, everything
works fine. If however, once a link is established, if you have to remove
that link, it doesn’t work as expected. Discovered this by:

* creating a document in English (E1)
* creating a French version (F1) using the Babel button
* duplicating the English document (E2)
* E2 is still linked to F1
* Unlink documents
* Create new F2
* Preview E1
* Click on Français link
* You’re taken to page F1

I’ve been able to reproduce this, and the following

* Create E3 from scratch
* Create F3 with Babel button
* Return to E3 and unlink
* Create F4 from E3 page with Babel button
* Preview E3
* Français button still takes you to F3 rather than F4

**Comment by goldsky** [comment]
https://github.com/mikrobi/babel/commit/164a83cb4ebeaa57c86315dd9a187ee9c6125c3f
