### ISSUE TITLE
Linking resources in modx 2.4, original resource changes context. 

### ISSUE THREAD

**Issue by BigBlockStudios** [mikrobi/babel#114]
If I create two resources, one in my FR context and the other in my EN context, open the EN resource and link it to the FR context. The document in the FR context will move to the EN context in the resource browser. 

checking the database, the resource HAS changed contexts. it can be dragged back to the correct context but.  that's not a long term solution really.

**Comment by intersel** [comment]
My experience (2.4.1)
After you link the resource with the EN context, don't save the resource...
The resource change context only if you save the resource...
If you don't, and reload the manager page, everything sounds ok...

It's like the call to babel changes the context of the page you just linked and so if you save it, it changes its context...

**Comment by tassu** [comment]
Same here in Modx 2.4.2. Newest Babel installation.

**Comment by letamtam** [comment]
We experiment the same problem. If we create a translation in another context, the problem doesn't appear. Only if I link after moving. Saving, not saving before kinking doesn't change the problem

**Comment by carnevlu** [comment]
Same for me. 
Somebody understand/imagine where the logic fail? I'm not sure that is a *bug* Babel, maybe MODX ?

i tried to understand the origin, but:
- the plugin, an the switch case `OnDocFormSave` appear to be ok,
- the `synchronizeTvs` method in the object Babel too.

Any idea inputs?

**Comment by degoya** [comment]
does anyone found a solution for this problem yet?
