### ISSUE TITLE
Mark related ressources if original resource has been modified

### ISSUE THREAD

**Issue by Gallenkamp** [mikrobi/babel#116]
I just edited my german language landing page. If i look at the related english version of that pade, there is no indicator that tells me that the original resource has been modified. So if I was a translator, I had to search for changes in all ressources or have a list, sent from the guy who edited the original language.

An indicator, maybe even in the menu, would be great. "Out of date".

**Comment by goldsky** [comment]
This will be tricky, because all translated resources are originals, from
their point of views.

**Comment by Gallenkamp** [comment]
Its simple (at least in my imagination):

"English" is original.
"German" and "Dutch" are translations.

If (modified<(my_brother_document(en))) {
tell_me("Please update translation xyz");
insert_class("alert", babel button)
}

**Comment by goldsky** [comment]
I don't think this is logical, because the linked translations don't have valid arguments of which one is obsolete. If I add this, then a typo fix can make a headache.
