### ISSUE TITLE
Access Control - Remove Link-List from Users/Groups...

### ISSUE THREAD

**Issue by domindian** [mikrobi/babel#118]
It should be a common situation: 
1. There is one usergroup A with access to all contexts and
2. there is one usergroup B with access to only one single context (the group is responsible for administrating that context) 

In that scenario the Babel-Menu in the manager shows all links to all contexts even if current usergroup does only have "load only" ACL right on any other contexts.

In my experience this results in enabling users from usergroup B to access and view (and save) resources from other contexts.

While the ability to view and save resources from other contexts may be solved with finer grained ACLs, is there a way to hide the Babel-Dropdown Menue from some user/groups alltogether?

kind regards

**Comment by domindian** [comment]
The links to translations in other contexts in general can be hidden if the TV (babelLanguageLinks) is i.e. put into a category the usergroup has no "view" right. This way the babel menu looks like there aren't any translations set up. But how can all other contexts be hidden from the menue, or why are they shown, if the is only the "load" permitted for other contexts in the ACLs?

**Comment by Jako** [comment]
This is (maybe) fixed with 3.3.0. Please reopen if that's not the case.
