### ISSUE TITLE
 [[BabelLinks]] not show anything in frontend

### ISSUE THREAD

**Issue by ogglin** [mikrobi/babel#119]
I create a contexts, installed Babel 3.0.0-beta4 (March 25, 2015) first time on new site.
In template I put `<ul> [[BabelLinks]] </ul>`, but on frontend i see just `<ul> </ul>`.

What can be wrong? Someone faced with similar?

**Comment by goldsky** [comment]
Have linked the resource to its translation?
If you want to ignore it, add &includeUnlinked=`1`

**Comment by ogglin** [comment]
Yes I have. And also i tried add &includeUnlinked=`1`. I don't understand, why showing a blank tag and no errors.

**Comment by goldsky** [comment]
Try one of these:
showUnpublished
showCurrent
includeUnlinked
ignoreSiteStatus

**Comment by ogglin** [comment]
Thanks, showCurrent is work, but just one showCurrent.

I will continue to look for the cause.
