### ISSUE TITLE
hreflang Link for Google needs other value than cultureKey

### ISSUE THREAD

**Issue by sonicpunk** [mikrobi/babel#120]
In one of my projects I am correcting the hreflang links in the head tag of the website according to the Google specs:
https://support.google.com/webmasters/answer/189077?hl=en

Currently in Babel, we only have the cultureKey to work with when outputting the language to the frontend for links.

In my project, I already am using 'en', 'de' as my CultureKey and this value is being used in the frontend for my links.

In my hreflang links in the header, I can only output these CultureKeys, which does not output what I need for Google.  For example instead of 'en', I need 'en-GB'.

One idea was to add a new context setting called hreflang, and then change the Babel snippet to also output this setting to the chunk template.  

Anyone have another idea?  As I am sure many may have the same problem, maybe it makes sense to extend Babel and allow it to process other given context settings?

**Comment by degoya** [comment]
doesn't something like this output modifier does the trick?
[[+cultureKey:is=`en`:then=`en-GB`:else=`de-DE`]] 

or a small snippet that returns the locale by countrycode

**Comment by sonicpunk** [comment]
That is also an idea that would work! I was just thinking that since Babel is handling this output, that it may benefit others if it was built into the plugin!

**Comment by degoya** [comment]
ofcoz it would be nice if this could be managed by babel itself already

**Comment by sonicpunk** [comment]
I will for now just solve it by writing a small output filter as you suggested

**Comment by degoya** [comment]
i thinked about more about it, there is a better solution. 
just add a setting to each of your context that holds the locale like

German Context:
countrycodelocale = de-DE

English Context: 
countrycodelocale = en-GB 

and output the setting with [[++countrycodelocale ]] in your header. 
for this solution you don't even use a output modifier or babel implementation.

**Comment by sonicpunk** [comment]
If I just output a context setting, it will show the one assigned to that context and not the correct corresponding language context.  

if my user is on the German page with context setting set to de-DE, then in the head tag it will output de-DE instead of the correct linked language en-GB, for example.

**Comment by degoya** [comment]
ahh yes you are absolutly right.

then you need to use a snippet like this to get the datas from the setting by key

$ctx = $modx->getContext($key);

if ($ctx) {
     $value = $ctx->getOption('countrycodelocale', null, 'en-GB');
}
