### ISSUE TITLE
modx babelLInks not showing up in Babel 3.0.0-rc1

### ISSUE THREAD

**Issue by berj** [mikrobi/babel#129]
Modx 2.5.0
Babel 3.0.0-rc1
PHP : 5.6.23
MySql : 5.6.30
context => web (fr)
context => english (en)

Before installing Babel on live server, I install it on my local server (MAMP Pro) and I follow the guide on «https://anyscreensize.com/blog/modx-multilingual». Everything works fine.

I do the same installation on a live server and the only thing that does not working is « BabelLinks ».

BabelLinks does not display links.

I am using this call (the same on my local server) :

<ul>
[[BabelLinks]]
</ul>

and the result is :

<ul>

</ul>

Clearing the cache, change nothing.

Thank you for your help

**Comment by goldsky** [comment]
Does it still occur?

**Comment by berj** [comment]
It is OK now.

From memory, I completely removed Babel and I reinstalled it. That solved my problem.

Recently I upgrade to Modx 2.5.2 and Babel still working perfectly.

Thank
