### ISSUE TITLE
Tagger Tags will not be copied to new language

### ISSUE THREAD

**Issue by designmich** [mikrobi/babel#130]
If i create a new language of an resource everything will be copied except Tagger Tags. Its very hard to add many tags to every language

**Comment by designmich** [comment]
If i duplicate an resource the tags will be copied as expected

**Comment by goldsky** [comment]
Tagger Tags in not a TV, so it's beyond Babel's features.
BUT, there'll be a new feature in Babel: event. https://github.com/mikrobi/babel/commit/6dfb1e6e7dec8b293e34d795c40f1080cd29b6bb

So you can later create a plugin to copy over the Tagger's value into the resource copy.
