### ISSUE TITLE
When creating a translation, the duplicated resource does not show up in resource tree

### ISSUE THREAD

**Issue by sonicpunk** [mikrobi/babel#131]
I have the problem within a particular collection, that when I try to translate one of the children, the duplicated resource is not shown in the resource tree of the linked context.  The id also does not show up in the Babal CMP tool.  I am guessing that the show_in_tree setting gets set to 0. I will look into it further.  

MODX 2.5 and Babel 3.0.0 rc-1

**Comment by sonicpunk** [comment]
I looked into the database, and it not only sets show_in_tree to 0, it also sets deleted to 1!!!

**Comment by sonicpunk** [comment]
When I turn off Collections  on both parents in both contexts, it seems to work again

**Comment by goldsky** [comment]
so, is it Babel's issue or Collection's?
