### ISSUE TITLE
MODX 2.5.1 compatible?

### ISSUE THREAD

**Issue by sonicpunk** [mikrobi/babel#132]
After Updating to 2.5.1 I have lots of issues with the language switching script from Babel on the frontend.  The link correctly writes, but modx does not go to the page when the link is pressed.  It just reloads the current page.

**Comment by degoya** [comment]
i'm using Babel 3.0.0-rc1 on a 2.5.1 install and everything seems to work fine. did you get the problem sorted?

**Comment by sonicpunk** [comment]
I believe it was a caching issues, as usual.  It was sorted out :)
