### ISSUE TITLE
Unable to link translations by searching by pagetitle

### ISSUE THREAD

**Issue by zaigham** [mikrobi/babel#139]
Please see the image below:
![image](https://cloud.githubusercontent.com/assets/114390/18830878/2a590a0a-83fc-11e6-946d-12bec18b0d18.png)

**Comment by zaigham** [comment]
It seems the clicking on the search item in `... or Pagetitle of target:" is not setting up input value, and its blank on pressing Save.

**Comment by zaigham** [comment]
Adding this code back in, make it work.
https://github.com/mikrobi/babel/blob/eec838fd0bbb4ec6c59fe651df5fb04b4a67ceb2/assets/components/babel/js/babel.class.js#L235-L255

**Comment by navtsi** [comment]
Didn't work for me. Copy code in file. Do I have to do more, like reinstalling or clear cache??
![bildschirmfoto 2016-10-25 um 08 25 53](https://cloud.githubusercontent.com/assets/10669843/19675093/ad19412a-9a8c-11e6-8ad3-1dd06943a57a.png)

**Comment by zaigham** [comment]
https://github.com/mikrobi/babel/pull/140/files
Please take this file from above PR and place in there. It should work to restore "search by title" feature.

**Comment by degoya** [comment]
i tired on modx 2.5.1 with the file from the PR but still doesn't fixes the problem
when i try to drag the id from the tree i get the same result. Resource not specified.

**Comment by zaigham** [comment]
How are you copying the file? Are you clearing cache/browser cache after it?
Try this, it is a direct link to the file: https://raw.githubusercontent.com/zaigham/babel/d125e07d28817ea6c04839475686a6fdcd3c25b0/assets/components/babel/js/babel.class.js

**Comment by degoya** [comment]
i tried again and the linking by name selected from the resource list works. the drag and drop from the sidebar still gives me the error "no resource specified".

**Comment by zaigham** [comment]
I could be wrong, but I think drag n drop is not supported.
