### ISSUE TITLE
500 error "No valid context specified" in Safari only

### ISSUE THREAD

**Issue by claytonk** [mikrobi/babel#141]
Very weird issue. Attempting to access my domain via Safari produces a 500 error unless I manually extend the URI. In other words, attempts to access http://316stage.com via safari produces a 500 error with the message "ERROR @ /server/path/www/core/model/modx/modx.class.php : 2310) No valid context specified". This only seems to happen in Safari, Firefox and Chrome work just fine. If I manually alter the URI to contain any value, say http://316stage.com/x then I'm sent to my error page normally and the site works.

Huh?

**Comment by claytonk** [comment]
Sorry, should have specified:

Server: NGINX (MODX Cloud)
MODX Version: 2.5.1
PHP Version: 5.6.26

My setup follows the Babel documentation to the T and works just fine everywhere but Safari.

**Comment by goldsky** [comment]
How did you setup the redirect in the conf file?

**Comment by claytonk** [comment]
Sorry, can you clarify? I'm not catching your question.

**Comment by goldsky** [comment]
Something like this https://www.nginx.com/blog/creating-nginx-rewrite-rules/

**Comment by claytonk** [comment]
Using the default NGINX server rules from MODX Cloud:

location / {
    try_files $uri $uri/ @modx-rewrite;
}

I don't have any other rewrites in place.

Unfortunately, this is now pretty urgent as the site is going live. Any help would be appreciated.

**Comment by claytonk** [comment]
Fixed this using LangRouter, so I think I'm good.
