### ISSUE TITLE
Grouping Contexts

### ISSUE THREAD

**Issue by sonicpunk** [mikrobi/babel#142]
Is there a way to group contexts together, so that you could use contexts for different websites and different languages?

For example have website A German (context) and website A English (context) along with website B German (context) and website B Englisch (context).  Then in Babel tell it that context A German and A English belong together and website B German and website B English belong together.  This way the button to swap and link resources together only show grouped contexts.

**Comment by goldsky** [comment]
AFAIK, this really depends on MODX core's feature to have nested contexts.
I am not sure it has been implemented programatically, IIMW there is a
"parent" field in context's table.

**Comment by sonicpunk** [comment]
There is a systems settings in babel where you add the contexts.  If this setting was a context setting instead?  Then you could have specific connections between contexts, in theory. Idea?

**Comment by DESIGNfromWITHIN** [comment]
Any update on this, really need this for a project.

**Comment by DESIGNfromWITHIN** [comment]
Fixed with:

`en,de,fr;en-site_2,de-site2`

**Comment by sonicpunk** [comment]
How fixed?  What did you do?

**Comment by Jako** [comment]
Grouping contexts is possible now.
