### ISSUE TITLE
Link to a translation with entering the ID instead of selecting the knot

### ISSUE THREAD

**Issue by navtsi** [mikrobi/babel#143]
I have a lot - more than 150 - resources to link to a translation. To select the knots in the tree it's not a uesefull way, because the list seams endless. But I have al list with corresponding IDs.

It would be easier to enter the ID than searching the knot in the resource tree. Is there a way just enter the ID in the field. Perhaps to deactivate JS part?

**Comment by zaigham** [comment]
https://github.com/mikrobi/babel/pull/140/files
Please take this file from above PR and place in there. It should work to restore "search by title" feature.

**Comment by navtsi** [comment]
This solves only the »search by title«, but not my problem. First, the list shows only 20 items, and I have round about 150. Second, I don't know the beginning letters of the translated pagetitle. But the »search by title« only looks for the beginning of the pagetitle. For example, if I enter »tech« it will find »Technical University of...« but not »Sciences and Technology...«.

**Comment by zaigham** [comment]
Then the drop down needs to be fixed, for pagination.

**Comment by digitalpenguin** [comment]
+1
Also if using collections the resource you may want to link to won't be in the tree.
You should be able to type in the resource ID to link to an existing resource.

**Comment by zaigham** [comment]
@goldsky how does it work now?
