### ISSUE TITLE
unlink resource translate

### ISSUE THREAD

**Issue by brescianicri** [mikrobi/babel#144]
When i unlink a translate of one context delete all traslation of the current resource. And delete the unlink of this resource. In the database the TV is empty alfer delete.

**Comment by brescianicri** [comment]
The babel-3.0.0-beta4 work

**Comment by goldsky** [comment]
It's meant to be like that.
If you un/link a translation, then all siblings' connections will be
deleted/created.

**Comment by goldsky** [comment]
however, it does not delete the other translations, only unlinks them.

**Comment by brescianicri** [comment]
Yes i meant unlink translation, but doesn't work. In the babel-3.0.0-beta4 the unlink in the current resource work but in the other resource all trstation go unlink. And we can't found resource with the research.

**Comment by brescianicri** [comment]
Fore example i connect 3 resource:
![image1](https://cloud.githubusercontent.com/assets/6154903/20532657/14ba018e-b0db-11e6-8140-bbbb246a23b3.png)
I want unlink DE link traslation:
![image2](https://cloud.githubusercontent.com/assets/6154903/20532677/25107086-b0db-11e6-92ec-00c5941d8adb.png)
The resoult is:
![image3](https://cloud.githubusercontent.com/assets/6154903/20532687/2ca53cc8-b0db-11e6-99ed-65b82873d274.png)
is wrong!

**Comment by brescianicri** [comment]
I resolve this issue with this update at line 118
replace this 
`$this->modx->babel->updateBabelTv($diff, $diff);`
whit this 
`$this->modx->babel->updateBabelTv($linkedResources, $linkedResources);`

**Comment by goldsky** [comment]
I dont understand your logic.

My understanding is like this:
- **Dutch is linked with English**
- anything unlinked with Dutch should also unlinked with English.
- and anything linked with Dutch should also linked with English.

**Comment by brescianicri** [comment]
If i link Italian page with Dutch and English if i unlink the connect with Dutch, i don't want unlink with English
