### ISSUE TITLE
Customize manager drop down selection

### ISSUE THREAD

**Issue by jchirschy** [mikrobi/babel#150]
Hi @goldsky

In some situations, the cultureKey / language is shared amongst a few contexts. For example, with some contexts like fr-fr, fr-be or en-ie. In those examples, the same lexicon may be used whatever the IANA's Language Subtag Registry.

Is it possible to handle the text displayed on the dropdown selection in the manager, which something more like `Context description` or with some system settings. May refer #107 

Thanks for your help

**Comment by goldsky** [comment]
at the end, you need to create different **cultureKey** settings into each context.
so I don't follow your saying "same lexicon may be used".

that said, the lexicon's structure should be

- mypackage/
    - lexicons/
         - en-ie/
         - fr-fr/
         - fr-be/

But I'll think about customizing manager down down selection.

**Comment by tartakxg** [comment]
Thanks for your work.
In previous versions it was more convenient to use cotextKey instead of the cultureKey in dropdown menu
