### ISSUE TITLE
Target Language Links

### ISSUE THREAD

**Issue by Gallenkamp** [mikrobi/babel#154]
When I visit my website which is primarily written in german, I see the links to "englisch" and "französisch". Which I can only read when I can read german. If my primary language was thai of chinese, visitors would never find the translation links.

I changed the lexicon strings to the targets version of the language "english" and "français", so the target audience can find them. In my opinion, that should be the default setting in Babel.

**Comment by goldsky** [comment]
the problem is that we don't have all the lexicons for all languages.
anyhow, you can still use the old chunk as: https://github.com/mikrobi/babel/wiki/Babel.BabelLinks#babellink-chunk
```
<li>
    <a href="[[+url]]" class="[[+cultureKey]][[+active:notempty=` [[+active]]`]]">
        [[%babel.language_[[+cultureKey]]? &topic=`default` &namespace=`babel`]]
    </a>
</li>
```

**Comment by Gallenkamp** [comment]
I changed the lexicon strings accordingly. The default chunk will only display the non translated language names.

How about setting a lexicon string like %self ? So french would be francais, german would be deutsch, spanish would be espanol (with all the accents of course)
