### ISSUE TITLE
Add header chunk

### ISSUE THREAD

**Issue by Gallenkamp** [mikrobi/babel#155]
To have a nice SEO working html header, we need 

```
<link rel="alternate" hreflang="en" href="[[~[[BabelTranslation? &contextKey=`web`]]? &scheme=`full`]]" \/\>

<link rel="alternate" hreflang="de-default" href="[[~[[BabelTranslation? &contextKey=`de`]]? &scheme=`full`]]" />
```

[MODX forums post on this](https://forums.modx.com/thread/97737/solved-hreflang-attribute-for-multilingual-websites-with-babel-2-contexts)

So we need a simple solution that places the current language and all available translations inside the header.

**Comment by Gallenkamp** [comment]
Header chunk including the current language

<link rel="alternate" hreflang="[[++cultureKey]]" href="[[~[[*id]]? &scheme=`full`]]" />
[[BabelLinks? &tpl=`hreflangTemplateChunk`]]

**Comment by Gallenkamp** [comment]
Hreflang has no default value. We could use a system setting for that like
```
<link rel="alternate" hreflang="[[++hreflang]]" href="[[+url]]" />
```
So that you can put **x-default** into the context that should serve as default language. Babel does not provide the +hreflang placeholder, so only ++hreflang would work. Only, if the current page is in the default language.

**Comment by goldsky** [comment]
@mikrobi mind to add @Gallenkamp as collaborator or wiki editor (I don't have permission to change this).

**Comment by mikrobi** [comment]
@goldsky done! Welcome onboard @Gallenkamp! 🎉

**Comment by goldsky** [comment]
ha! didn't realize that you both are in germany. lol.
go ahead @Gallenkamp , add https://github.com/mikrobi/babel/issues/153 to wiki as well

**Comment by mikrobi** [comment]
🇩🇪

**Comment by degoya** [comment]
are there any news on this? did someone worked out a solution for language headers?
