### ISSUE TITLE
babel 3.0.0 and git doesn't work

### ISSUE THREAD

**Issue by jdaehne** [mikrobi/babel#156]
Using git and babel 3.0.0 won't work for me. While trying to add files to commit, i receive the following errors:

$ fatal: Not a git repository: core/components/babel/vendor/iana-language-subtag-registry/../../../../../.git/modules/core/components/babel/vendor/iana-language-subtag-registry/

and

$ fatal: Not a git repository: core/packages/babel-3.0.0-pl/modCategory/4be5f79c620b06f9dc090a0f0701adfc/1/babel/vendor/iana-language-subtag-registry/../../../../../.git/modules/core/components/babel/vendor/iana-language-subtag-registry/

After deleting the ".git" files in the named directories everything works fine.

**Comment by sscWhitevision** [comment]
yes, same problem here.

git add --all

and then:
fatal: Not a git repository: core/packages/babel-3.0.0-pl/modCategory/4be5f79c620b06f9dc090a0f0701adfc/1/babel/vendor/iana-language-subtag-registry/../../../../../.git/modules/core/components/babel/vendor/iana-language-subtag-registry/

and here:
fatal: Not a git repository: core/components/babel/vendor/iana-language-subtag-registry/../../../../../.git/modules/core/components/babel/vendor/iana-language-subtag-registry/

please delete the .git files in these directories, thx.

**Comment by Jako** [comment]
The current code changed a lot. So I am closing this.
