### ISSUE TITLE
[feature request] Allow linking resources programmatically

### ISSUE THREAD

**Issue by delleyma** [mikrobi/babel#165]
Hello, 
Thanks for the great plugin.
I didn't find any way to link resources from code.
I'm creating resources in each context from my plugin and it would be great to link them automatically after creation.

Is there any way to do it yet ? Like an API access to linking methods.

I could help implementing it if needed. 
Thanks for your help

**Comment by Jako** [comment]
It is not that easy with the past and the current code.
