### ISSUE TITLE
500 errors when opening page in manager

### ISSUE THREAD

**Issue by hugopeek** [mikrobi/babel#167]
Probably related to issues #152 and #166.

For me, whenever I open one specific page in the manager, I get a blank screen. Happens client side also and they reported this before 2.6.5 update already.

I ported all the content to a different install and still same page is getting a 500 error. Disabling the Babel plugin or the OnDocFormPrerender event immediately fixes this. And if I duplicate the page in both contexts and link those again, it works fine also.

There's nothing in the MODX error log, but found the following in the NGINX log:

```
2018/07/31 12:19:48 [error] 30261#30261: *5785 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/hugo/Localhost/hs-upgrade/core/components/babel/model/babel/babel.class.php:583
Stack trace:
#0 /home/hugo/Localhost/hs-upgrade/core/cache/includes/elements/modplugin/100019.include.cache.php(81): Babel->getMenu(Object(modDocument_mysql))
#1 /home/hugo/Localhost/hs-upgrade/core/model/modx/modscript.class.php(70): include('/home/hugo/Loca...')
#2 /home/hugo/Localhost/hs-upgrade/core/model/modx/modx.class.php(1608): modScript->process(NULL)
#3 /home/hugo/Localhost/hs-upgrade/manager/controllers/default/resource/resource.class.php(160): modX->invokeEvent('OnDocFormPreren...', Array)
#4 /home/hugo/Localhost/hs-upgrade/core/model/modx/modmanagercontroller.class.php(158): ResourceManagerController->firePreRenderEvents()
#5 /home/hugo/Localhost/hs-upgrade/core/model/modx/modmanagerresponse.class.php(74): modManagerController->render()
#6 /home/hugo/Localhost/hs-upgrade/core/model/modx/modmanagerrequest.class.php(183):" while reading response header from upstream, client: 127.0.0.1, server: hs-upgrade.loc, request: "GET /manager/?a=resource/update&id=275 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "hs-upgrade.loc", referrer: "http://hs-upgrade.loc/manager/?a=resource/update&id=350"
```

Line 81 in the Babel plugin:

```
$babel->config['menu']           = $babel->getMenu($resource);
```

And indeed, disabling this line will solve the issue too (but without the top menu being loaded of course). I checked with is_object if $resource is still an object in PHP and that seems to be the case.

Anyone have any clues to what's going on here?

**Comment by hzuellig** [comment]
It guess it must be somehow connected with the updating process. I did a fresh install of another site (version 2.5.6) and imported the database. Fresh installation of all plugins including babel as well and this works fine.

**Comment by jaygilmore** [comment]
This may be related to this discussion here: https://modxcommunity.slack.com/archives/C042Q4YS7/p1559641620011500

```I mean, one colleague installed babel and linked resources to the other context. I removed these resources from the context and uninstalled Babel because at the time we didn't need it yet and it was misconfigured. Now, when I installed Babel again, these links persisted and as the resource doesn't exist, the error occurred.

I solved the issue going to the Babel menu where all the resources appear I have made "unlink" of them all, I have linked them again and now it seems to work.```

**Comment by Oetzie** [comment]
Line 583 in babel class: 
```
$linkResource  = $this->modx->getObject('modResource', $linkedResources[$contextKey]);
$resourceTitle = $linkResource->get('pagetitle');
```

So the linked resource does not exists, this can occure because the resource is deleted or the user has not the right permissions to `load/view` the linked resource.
