### ISSUE TITLE
babel box trouble...

### ISSUE THREAD

**Issue by sergekolesnikoff** [mikrobi/babel#170]
After executing the instructions and successfully installing the package, the babel box does not appeared...
How to check the installation? Status - succesfull... but - no language boxes to copy or link resources... (
Сan not find any information about it... Help me if you can! ) Thx!

**Comment by degoya** [comment]
any errors in the logs? modx, php browser?
did you setup the context right? 
are the context added to the babel system configuration?

**Comment by sergekolesnikoff** [comment]
> any errors in the logs? 
no error displayed after installation... 

> modx, php browser?
logs?

> did you setup the context right?
i try to do like in instruction ) it may be hoster trouble? 

> are the context added to the babel system configuration?
on babel installation it automatic added my context... "eng, web" - in my case...

on all instruction says - do that and the buttons appeared... but not in my case...

what i do wrong - can not understand...

i'm just start work with modx... and it is different after other cms )

**Comment by Jako** [comment]
Closed due to lack of response.
