### ISSUE TITLE
Ability to add context_key in the translations list

### ISSUE THREAD

**Issue by sdrenth** [mikrobi/babel#180]
I'd like to have the ability to a add context_key in the translations list in the manager page:
![Screenshot 2019-12-16 at 11 25 26](https://user-images.githubusercontent.com/7802465/70899375-c83bce80-1ff6-11ea-8275-8be5da305b7f.png)

This could be very helpfull when you have multiple contexts which use the same language for different countries, for example:
Dutch for the Netherlands
Dutch for Belgium
French for France
French for Belgium

**Comment by duron16** [comment]
Change in file "core/components/babel/model/babel/babel.class.php" string 593:
'displayText'   => $languages[$cultureKey]['Description'].' ('.(!empty($cultureKey) ? $cultureKey : $contextKey).')',

**Comment by Jako** [comment]
This is possible with 3.2.0.
