### ISSUE TITLE
Can't edit other language

### ISSUE THREAD

**Issue by Sybrenb** [mikrobi/babel#181]
When I press this button, nothing happens. I also didn't get an error.

![Schermafbeelding 2020-06-05 om 14 49 50](https://user-images.githubusercontent.com/21313464/83878183-06ab7e00-a73c-11ea-9074-91e2e0ee7e8b.png)

What can be wrong?

![Schermafbeelding 2020-06-05 om 14 50 05](https://user-images.githubusercontent.com/21313464/83878190-09a66e80-a73c-11ea-98bb-54e4b73f440c.png)

**Comment by degoya** [comment]
is babel_contentKeys "nl" missing?

**Comment by duron16** [comment]
What in browser console?

**Comment by Jako** [comment]
Closed due to lack of response.
