### ISSUE TITLE
It is necessary to replace icons with fonts

### ISSUE THREAD

**Issue by Ruslan-Aleev** [mikrobi/babel#182]
https://github.com/mikrobi/babel/blob/fd82305108487e058a9d343dc893fdff66e636c5/core/components/babel/lexicon/en/cmp.inc.php#L41

- Firstly, it will be easier to define icons through `<i>` or just an additional class.
- Secondly, the `/manager/` url can be changed during the installation process.

**Comment by Jako** [comment]
This is fixed with 3.2.0
