### ISSUE TITLE
Language is not showing in the dropdown

### ISSUE THREAD

**Issue by JBtje** [mikrobi/babel#184]
The URL from the readme is offline: http://www.multilingual-modx.com/blog/2011/multilingual-websites-with-modx-and-babel.html
making it a bit difficult to follow the instructions correctly...

My website is fully Dutch and `cultureKey` is set to `nl`. I added a new context `en` and installed babel with the `contextKeys` = `web,en`.
When i go to any document, it shows the button "Englisch (en)" on top (left of save). Hovering the button gives one dropdown item "Englisch (en)" with 2 options: create / link.

If i select create, it create a copy of the document under the correct context `en`.

However...

If i go to `Menu -> Extras -> Babel` it does not show any page (or option) under the column `web`, whilst the screenshot on the modx.com site https://modx.com/assets/image-cache/extras/4d556d09b2b083396d000f7d/babel-3.0.0-rc1.5bf76cc9.png does show items under `web`.

Furthermore, on the screenshots on the modx.com site, I see "English (web)" as option in the dropdown (right top, left of save), so i would expect to see something like "Dutch (web)", but that does not exist...

Lastly, `[[BabelLinks]]` does not return anything.

Any suggestions?

**Comment by Jako** [comment]
The system setting is `babel.contextKeys` and not `contextKeys`.
