### ISSUE TITLE
No official documentation available

### ISSUE THREAD

**Issue by Schtailian** [mikrobi/babel#187]
Hi,
i am building a new site on modx and saw that no real documentation is available.

- There is only [this site](https://docs.modx.com/current/en/extras/babel/index), which tells you how to install it.
- This site links to [that site](http://www.multilingual-modx.com/blog/2011/multilingual-websites-with-modx-and-babel.html) which is not available.

I think this should be in the official docs and not on a separate site.

Let me know how you want to deal with this. I would be happy to take on this work.

**Comment by Teddy0927** [comment]
After two years, this problem still remains. The documentation seems outdated and required to update the reference website. The author could also takes Schtailian's recommendation and put everything we need to know in the MODX official documentation. Please help MODX new users like me to get good at this CMS! Thank you...

**Comment by Jako** [comment]
It is now available: https://mikrobi.github.io/babel/
