### ISSUE TITLE
404 Page not found - on every translation

### ISSUE THREAD

**Issue by MarinAndrew** [mikrobi/babel#190]
Hello and please help me. I'm noobie in MODX and this is my first exeprience. Have installed Babel step-by-step (https://modx.pro/howto/16334 and https://cat-art.ru/blog/multiyazyichnost-modx-revo). My site needs to be translated in to 3 languages (ru / en / ro), Russian is default. I have added additional Context and created al translational resources. Then I made connections between every resource in each language. Also, I changed Alias of translated resources (for better SEO). When try to load any translated resouce it gets a 404 error, only the default language pages work fine.

**Example:**
http://novadsail.com/o-nas/ (200)
http://novadsail.com/en/about-us/ (404)
http://novadsail.com/ro/despre-noi/ (404)

What can be wrong? Maybe there is a problem in .htaccess file?

```
# // With these Rules, Index page doesn't opens = ERR_TOO_MANY_REDIRECTS // #

# RewriteCond %{HTTP:Accept-Language} ^ru [NC]
# RewriteRule ^$ /ru/ [R=301,L]

# RewriteCond %{HTTP:Accept-Language} !^ru [NC]
# RewriteRule ^$ /ru/ [R=301,L]

# // Working part // #

# redirect all requests to /en/favicon.ico  to /favicon.ico
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(en|ru|ro)/favicon.ico$ favicon.ico [L,QSA]
 
# redirect all requests to /en/assets* to /assets*
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(en|ru|ro)/assets(.*)$ assets$2 [L,QSA]
 
# redirect all other requests to /en/* 
# to index.php and set the cultureKey parameter
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(en|ru|ro)?/?(.*)$ index.php?cultureKey=$1&q=$2 [L,QSA]
```

![Friendly_urls](https://user-images.githubusercontent.com/98874525/174057403-9a0277cd-9297-4d16-a4cf-4ee3a291efe6.jpg)
![System_Options](https://user-images.githubusercontent.com/98874525/174057377-fcde753e-d3b2-49f8-8007-a0b63cea1a3b.jpg)
![Context_Settings](https://user-images.githubusercontent.com/98874525/174057396-5de9d296-6e71-492a-b123-f618624613ea.jpg)
![Additional_Plugin](https://user-images.githubusercontent.com/98874525/174057401-291e2660-ecb1-4925-af8d-71e5d450bde5.jpg)
![Babel_Connections](https://user-images.githubusercontent.com/98874525/174057392-6f50ac24-e56d-482c-afc1-6eab990ed5fa.jpg)

**Comment by Jako** [comment]
A few links to cover this installation issue:

https://mikrobi.github.io/babel/usage/tutorial/
https://mikrobi.github.io/babel/usage/tutorial-seo/
An approach with SmartRouting/xRouting is shown on:

https://modx.today/posts/2015/05/using-xrouting-for-multilingual-websites-in-modx
