### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by duron16** [mikrobi/babel#193]
Hello.
At first, thanks you for cool extra!

I ran into a problem. I need change default language, with save url for SEO-optimization, exept main page. But I not find how do this. 
A few days I try different ideas and all them isn`t work. 
Default language now: 
![image](https://user-images.githubusercontent.com/14205100/178826068-ddeccca7-86b6-48b4-8632-7d92c4c042f6.png)

And this language should be made the default:
![image](https://user-images.githubusercontent.com/14205100/178826225-b5695688-2895-41ab-9e4c-c5e61b78e3c5.png)

When I edit base_url and/or change default context in gateway plugin, I see 404-error on the inner pages and the redirect goes into a loop on other language version.

Please help me )

**Comment by Jako** [comment]
A few links to cover this installation issue:

- https://mikrobi.github.io/babel/usage/tutorial/
- https://mikrobi.github.io/babel/usage/tutorial-seo/

An approach with SmartRouting/xRouting is shown on:

- https://modx.today/posts/2015/05/using-xrouting-for-multilingual-websites-in-modx
