### ISSUE TITLE
Modx 3.1.0 problems to show pages in babel plugin admin

### ISSUE THREAD

**Issue by lemaybetancourt** [mikrobi/babel#195]
I have problems displaying pages in babel plugin with modx 3.0 and higher, no errors are displayed but the page grid is empty( see image example attached).

![image](https://user-images.githubusercontent.com/98039770/198812904-2ce9bde1-089b-46a6-99fd-4b9cc735a1b7.png)

**Comment by Ibochkarev** [comment]
@JoshuaLuckers 
`[2022-12-03 01:13:09] (ERROR @ /home/i/infoba19/infoba19.beget.tech/public_html/core/src/Revolution/modX.php : 1788) Unable to load processor for action "mgr/resource/getMatrixList", it does not exist as an autoloadable class that extends \MODX\Revolution\Processors\Processor, and also not as a file in "/home/i/infoba19/infoba19.beget.tech/public_html/core/components/babel/processors/mgr/resource/getMatrixList.class.php"
`

**Comment by Ibochkarev** [comment]
https://github.com/mikrobi/babel/pull/192 - fix this error
