### ISSUE TITLE
Idea: redirect based on browser-language

### ISSUE THREAD

**Issue by bertoost** [mikrobi/babel#20]
I was thinking about a nice feature? It's maybe nice to create a sort of redirector plugin wich checks the browser language of the visitor and redirects them to the right context-site-url. In my case I have an "nl.domain.com" and "en.domain.com". Wen someone comes trough "www.domain.com" or just "domain.com", it would be nice if they redirects to the right part.

When a language is unknown in the contexts, just redirect to the first/default context.

**Comment by Jako** [comment]
gadamiak has done this: https://gist.github.com/gadamiak/3812853

Available as transport package on http://modx.com/extras/package/langrouter

**Comment by Gallenkamp** [comment]
Easy to do with htaccess:

```RewriteCond %{HTTP:Accept-Language} !^de [NC]
RewriteRule ^$ en/ [R=301,L]```

**Comment by Gallenkamp** [comment]
One big downside with this. You can't switch languages by choice.

So if you're visiting a website from a foreign computer, you're screwed. Also, some bots might never get to see the whole site with all languages.

**Comment by sebastian-marinescu** [comment]
This can be accomplished with a language-matching snippet like this: 
https://gist.github.com/sebastian-marinescu/4b2991bc40dbbc405257ba5846adb1ef

**Comment by Jako** [comment]
This is part of a routing extra and not part of Babel.
