### ISSUE TITLE
Feature request: New child translation seek for translated parent

### ISSUE THREAD

**Issue by arjen-t** [mikrobi/babel#206]
Isn't it an idea that when a child gets translated, to find the translated parent as the new parent instead of adding the translated child as an orphan to the resource tree?

**Comment by arjen-t** [comment]
Never mind, apparently Monday mornings are tough. I overlooked this behavior. 😆

**Comment by arjen-t** [comment]
hereby closed 😋

**Comment by Jako** [comment]
This happens when the parent does not exist in the translated context …

**Comment by arjen-t** [comment]
Yes, I realized that. A bit too hasty with giving feedback... :-p
