### ISSUE TITLE
BabelTranslation multiple ids for Resource

### ISSUE THREAD

**Issue by arjen-t** [mikrobi/babel#207]
In the past, I can remember that when filling in a resourceId comma-separated, you would receive all those resources back once translated. However, this does not seem to work anymore.

It appears that the casting of the default property, resourceId::int, is causing this issue. It casts the given resourceId, whether comma-separated or not, first to an integer. While examining the logic of the BabelTranslation snippet class, it seems that the logic supports comma-separated values for resource ids, but it always receives an integer and not a string.

**Comment by Jako** [comment]
The int casting happens here: https://github.com/mikrobi/babel/blob/master/core/components/babel/src/Snippets/BabelTranslation.php#L26C1-L27C1

Please remove the `::int` there. It will be fixed with the next version.
