### ISSUE TITLE
Issue with INT as STRINGS in 3.3.1

### ISSUE THREAD

**Issue by momon** [mikrobi/babel#210]
I recently updated to 3.3.1 and after doing so one of our sections which uses a custom plugin broke.

Upon debugging I realized the culprit was on a runSnippet request that looks like this:

```
            $translationId = $modx->runSnippet('BabelTranslation', [
                'resourceId' => $monitored_slugs[$alias_base], 
                'contextKey' => $ck,
                'showUnpublished' => 1
            ]);
```

In this call, the resourceId is coming from a prior defined array which contained ID's of documents to serve in different instances.  This snippet call was returning empty.

After a bit of troubleshooting I realized that sending over the resourceId as strings instead of integers immediately made it work and it returned to working as intended, so I opted to redefine my array and ensure all resourceIds are being sent as strings and not integers but that feels a bit weird.

I originally reported this to the MODx team as this only showed up after I upgraded to 3.0.5 but I later on arrived to the conclusion that the only reason I didn't realize it before upgrading was due to caching.  After clearing cache after the upgrade and realizing this snippet was also recently updated I am guessing the issue is there.  The snippet is expecting the resourceID to be sent as a string.

If that is intentional, that's perfectly fine but it feels a bit weird for me forcing integers as strings.

**Comment by Jako** [comment]
I faced that too in another installation and fixed it in my repo: https://github.com/Jako/Babel/commit/12c65a8f7d6d27540ae87a4cb10bdcf664f31b21

I haven't had time to release a new version yet. Sorry.

**Comment by Jako** [comment]
3.3.2 is released
