### ISSUE TITLE
Babel max context

### ISSUE THREAD

**Issue by rlnovodvorskiy** [mikrobi/babel#213]
If there are more than 20 contexts in the system, they are not displayed either in the table columns or in the drop-down list of contexts
And there are suspicions that because of this, lexicon dictionaries are not loaded for some contexts

![image](https://github.com/mikrobi/babel/assets/28018177/414525be-d8da-461f-8c30-c572daa73023)

In babel settings :
![image](https://github.com/mikrobi/babel/assets/28018177/6d657da4-c26a-4e53-896d-174456209a3b)

And babel table and context select:

![image](https://github.com/mikrobi/babel/assets/28018177/64aa25e9-c82a-42e1-ab24-8f7ee78a886a)

![image](https://github.com/mikrobi/babel/assets/28018177/1b6e9b1c-8201-46a5-a8d3-c6d9d6fdf410)

**Comment by Jako** [comment]
Fixed in 3.3.4
