### ISSUE TITLE
No sort parameter in BabelLinks 

### ISSUE THREAD

**Issue by Spaceknyte** [mikrobi/babel#215]
As for me, this parameter is very lacking, at least by contexts IDs. How can I do this myself?

**Comment by Jako** [comment]
According to the code the links are sorted by the order of the context keys in `babel.contextKeys`.

If you want to add an own sorting, you have to sort the $outputArray before the line https://github.com/mikrobi/babel/blob/3da449c346742b180f893ba61132ed00bc6fa2d3/core/components/babel/src/Snippets/BabelLinks.php#L153

If you prepare an acceptable solution (a private sort method in the BabelLinks class is suitable), I will add this to the repository.
