### ISSUE TITLE
Sync resource fields?

### ISSUE THREAD

**Issue by jenswittmann** [mikrobi/babel#218]
I have a site with 4 contexts (4 languages). When I unpublish a resource, I have to do the same manually for the other 3 related resources. Maybe we can add the resource field `published` to the `babel.syncTvs` system setting and sync this too? I will try to make a PR for this, but want to discuss it first 😸 

https://github.com/mikrobi/babel/blob/2dca0e0d7a853eea1bc1664715d50469d64b8243/core/components/babel/src/Babel.php#L327-L354

**Comment by jenswittmann** [comment]
> The synchronizeTvs method is executed in OnDocFormSave. So a synchronizeFields method has to be executed there too. An additional button line is superfluous then. (The current checkbox that enables the synchronization, too.)
> I am fine with a PR :breites_lächeln: 

@Jako i try a PR for this 🤞🏽

**Comment by Jako** [comment]
Added in 3.4.0
