### ISSUE TITLE
SyncTvs of TV Resources

### ISSUE THREAD

**Issue by andreij** [mikrobi/babel#33]
If the template variable is a Resource Id itself, I think that the syncTvs should work this way (TVR = Template Variable Resource):

- Check if there is a translation of the TVR on the context we are translating to:
  - If exists, then the syncTvs should save the TVR translated id,
  - If doesn't exists, the  syncTvs simply saves the original TVR.

Does it make sense?

**Comment by goldsky** [comment]
I'm closing this issue, pls open new one if the problem occurs
