### ISSUE TITLE
Better context key values on Apache modx_userdir

### ISSUE THREAD

**Issue by bertoost** [mikrobi/babel#35]
For example I have 3 languages/contexts

web = NL
de
en

I have setupped babel with subfolders like http://www.domain.com/en/ or ../de/ and that is working fine.

Only for local development we're using apache mod-userdir to have a public_html for every user on the local development machine. You get url's like http://local-machine/~user1/ and ../~user2/.. For example: http://local-machine/~user/Example.com/ and then you get ../Example.com/de/ and ../en/. Wich is working fine.

Only when working with multiple users there are some issues with the context settings done for each context. The context settings like "site_url" and "base_url" are set to user1 and so user2 cant see his local version.

To make this working would be great to add something like {base_url} inside the site_url setting. So for example: "{base_url}de/". This looks like it's working only the for the web context, and only when loaded as first. When you load "de/" first, then the "en/" link will be "de/en/" ...

I hope you understand and maybe we can get this working?

**Comment by Jako** [comment]
This is part of a routing plugin and not part of Babel.
