### ISSUE TITLE
FEATURE REQUEST: browser icons & additional variables copied over

### ISSUE THREAD

**Issue by BigBlockStudios** [mikrobi/babel#76]
Just a couple of feature requests,
- resource browser icons that indicate whether a resource has a translation or not _OR_ some kind of tool/reporting that indicates the same
- the option to copy publication dates and publish statuses when a translation is created. It's pretty cumbersome to go through 200 some odd resources 'fixing' publish date.

**Comment by depositado** [comment]
Especially the second one!
