### ISSUE TITLE
Babel-link not good, shows q= even with friendly url

### ISSUE THREAD

**Issue by funkyduke** [mikrobi/babel#98]
When I click the language-link then the url is the url I'm on with an addition of q=

f.e.: www.test.com/test/testpage-en?q=test/testpage-fr (this should be www.test.com/test/testpage-fr)

Everything works fine with older Babel.

**Comment by goldsky** [comment]
latest version?

**Comment by funkyduke** [comment]
https://github.com/mikrobi/babel/releases/tag/3.0.0-beta1

**Comment by funkyduke** [comment]
OK, I see now a version beta2. Sorry, will test this one first.

**Comment by funkyduke** [comment]
@goldsky works perfect now with beta2. Sorry.

Another small issue: wouldn't it be more logical that the translated link is in the language of the language itself. F.e.: I'm Dutch speaking. When I come on the English website then it says 'Dutch', this should be 'Nederlands', so already in the Dutch language. Or I'm I overseeing something?

**Comment by goldsky** [comment]
https://github.com/mikrobi/babel/blob/develop/core/components/babel/lexicon/en/default.inc.php#L72

**Comment by goldsky** [comment]
If you think it's incorrect, you can submit new issue, or fork this and fix
the translation, then ask for Pull Request.

**Comment by funkyduke** [comment]
@goldsky ok, but it's not an error, just a logical suggestion.

**Comment by goldsky** [comment]
No problem.
Post a new issue then, so I won't forget.
